# Generated by Django 6.1.1 on 2026-09-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='docto',
            new_name='doctor',
        ),
    ]
